# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helloers', '0005_auto_20151219_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 20, 11, 52, 57, 12751, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
